server:
  port: 8082

logging:
  config: classpath:config/logback-dev.xml

spring:
  application:
    name: user-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.92.140:3306/jws_user?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: jarvis_admin
    password: Quanli123
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate.ddl-auto: update
    show-sql: true
  redis:
    host: 
    password: 
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.jarvis.user.entity,com.jarvis.user.dto
  configuration:
    map-underscore-to-camel-case: true
    logImpl: org.apache.ibatis.logging.slf4j.Slf4jImpl

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
