@startuml
微信用户-> 业务系统采购或进销存:请求登录业务系统
业务系统采购或进销存-> 微信开放平台:请求微信OAuth2.0授权登陆
微信开放平台-->微信用户:请求用户确认
微信用户->微信开放平台:用户确认
微信开放平台-->用户中心:回调用户中心适配器接口，带上授权临时票据(code)
用户中心->业务系统采购或进销存:用户中心返回登陆成功标识和一段js，跳转到业务系统页面,带过来code
业务系统采购或进销存-->用户中心:php接口内部调用用户中心获取token接口
用户中心->微信开放平台:用户中心通过code加上appid和appsecret换取access_token
微信开放平台-->用户中心:微信返回access_token
用户中心->微信开放平台:用户中心通过access_token 获取用户信息
微信开放平台-->用户中心:微信返回用户信息，用户中心完成登陆认证
用户中心->业务系统采购或进销存:返回登陆成功的token，或者未绑定的消息+登陆流水号code，或者多机构类型的token
@enduml